### ISSUE TITLE
Awesome article, but code is choking on LdrpDrainWorkQueue

### ISSUE THREAD

**Issue by testpushhydra** [paskalian/WID_LoadLibrary#1]
Helper::SigScan is not finding the pattern referenced.

**Comment by testpushhydra** [comment]
FYI.. Windows version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      22621  0

**Comment by paskalian** [comment]
You're correct, the project was designed for a very specific Windows 10 version and my only purpose while doing it was trying to get better knowledge on the Windows API, if one or more pattern(s) do not get referenced that/those pattern(s) can be easily updated by opening up ntdll.dll on IDA, loading ntdll.pdb and searching all of them manually by name, that's how I did it.

Of course this can be automated by making the project download the latest ntdll.pdb from the internet and finding the references itself but didn't really see any use for that. Thanks for the issue. :)

**Comment by paskalian** [comment]
You're correct, the project was designed for a very specific Windows 10 version and my only purpose while doing it was trying to get better knowledge on the Windows API and sharing that knowledge with other people, if one or more pattern(s) do not get referenced, that/those pattern(s) can be easily updated by opening up ntdll.dll on IDA, loading ntdll.pdb and searching all of them manually by name, that's how I did it.

Of course this can be automated by making the project download the latest ntdll.pdb from the internet and finding the references itself but didn't really see any use for that. Thanks for the issue. :)
